# Generated by Django 5.2.3 on 2025-07-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TableHash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=255)),
                ("table_hash", models.CharField(max_length=64)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
