# Generated by Django 5.2.3 on 2025-07-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hash_app", "0002_tablehash_content_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModifiedTableHash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=255)),
                ("table_hash", models.CharField(max_length=64)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "content_hash",
                    models.CharField(
                        blank=True, editable=False, max_length=64, null=True
                    ),
                ),
            ],
        ),
    ]
