# Generated by Django 5.2.3 on 2025-07-08 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hash_app", "0003_modifiedtablehash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tablehash",
            name="content_hash",
        ),
    ]
