# Generated by Django 5.2.3 on 2025-06-23 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_center_app", "0002_alter_mediaitem_file"),
        ("question_app", "0003_questioncategory_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="image",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"media_type": "image"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="question_images",
                to="media_center_app.mediaitem",
            ),
        ),
    ]
