# Generated by Django 5.2.3 on 2025-06-24 23:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("question_app", "0004_alter_question_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True
            ),
        ),
    ]
