# Generated by Django 5.2.3 on 2025-06-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_app", "0005_alter_question_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="priority",
            field=models.IntegerField(default=10),
        ),
    ]
