# Generated by Django 5.2.3 on 2025-07-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_app", "0006_question_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="content_hash",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="content_hash",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="questioncategory",
            name="content_hash",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="questiontype",
            name="content_hash",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True
            ),
        ),
    ]
