# Generated by Django 5.2.3 on 2025-06-23 12:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media_center_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaitem",
            name="file",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True
            ),
        ),
    ]
