# Generated by Django 5.2.3 on 2025-06-20 22:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fitur_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
