# Generated by Django 5.2.3 on 2025-06-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitur_app", "0002_feature_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="max_age_in_days",
            field=models.IntegerField(
                blank=True, help_text="Maximum age in days", null=True
            ),
        ),
        migrations.AddField(
            model_name="feature",
            name="min_age_in_days",
            field=models.IntegerField(
                blank=True, help_text="Minimum age in days", null=True
            ),
        ),
    ]
