# Generated by Django 5.2.3 on 2025-06-26 13:11

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitur_app", "0003_feature_max_age_in_days_feature_min_age_in_days"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckupCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_kategori", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="feature",
            name="kategori",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fitur",
                to="fitur_app.checkupcategory",
            ),
        ),
        migrations.CreateModel(
            name="CheckupGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tanggal_lahir",
                    models.DateField(
                        blank=True, help_text="Tanggal lahir pengguna", null=True
                    ),
                ),
                ("nik", models.CharField(blank=True, max_length=16, null=True)),
                ("nama_ibu", models.CharField(blank=True, max_length=255, null=True)),
                ("nik_ibu", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "foto",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image"
                    ),
                ),
                (
                    "kategori",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fitur_app.checkupcategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
