# Generated by Django 5.2.3 on 2025-06-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitur_app", "0004_checkupcategory_feature_kategori_checkupgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkupgroup",
            name="nama",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
