# Generated by Django 5.2.3 on 2025-06-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitur_app", "0005_checkupgroup_nama"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkupgroup",
            name="tanggal_pendaftaran",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
