# Generated by Django 5.2.3 on 2025-06-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitur_app", "0007_checkupgroup_jenis_kelamin"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkupgroup",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
