# Generated by Django 5.2.3 on 2025-06-27 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alamat_app", "0001_initial"),
        ("fitur_app", "0008_checkupgroup_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkupgroup",
            name="desa_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="alamat_app.desa",
            ),
        ),
    ]
