# Generated by Django 5.2.3 on 2025-06-27 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fitur_app", "0009_checkupgroup_desa_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checkupgroup",
            old_name="desa_id",
            new_name="desa",
        ),
    ]
