# Generated by Django 5.2.3 on 2025-06-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitur_app", "0010_rename_desa_id_checkupgroup_desa"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="final_instructions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feature",
            name="initial_instructions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
