# Generated by Django 5.2.3 on 2025-06-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitur_app", "0011_feature_final_instructions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="requires_analysis",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether this feature requires analysis",
            ),
        ),
    ]
