# Generated by Django 5.2.3 on 2025-07-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitur_app", "0012_feature_requires_analysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkupgroup",
            name="content_hash",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="checkupgroup",
            name="hpht",
            field=models.DateField(
                blank=True, help_text="Hari Pertama Haid Terakhir", null=True
            ),
        ),
    ]
