# Generated by Django 5.2.3 on 2025-07-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitur_app", "0013_checkupgroup_content_hash_checkupgroup_hpht"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkupcategory",
            name="content_hash",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="feature",
            name="content_hash",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True
            ),
        ),
    ]
