# Generated by Django 5.2.3 on 2025-06-27 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KabupatenKota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Provinsi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Kecamatan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
                (
                    "kabupaten_kota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kecamatan",
                        to="alamat_app.kabupatenkota",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Desa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
                (
                    "kecamatan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="desa",
                        to="alamat_app.kecamatan",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="kabupatenkota",
            name="provinsi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kabupaten_kota",
                to="alamat_app.provinsi",
            ),
        ),
    ]
