# Generated by Django 5.2.3 on 2025-07-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alamat_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="desa",
            name="content_hash",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="kabupatenkota",
            name="content_hash",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="kecamatan",
            name="content_hash",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="provinsi",
            name="content_hash",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True
            ),
        ),
    ]
