# Generated by Django 5.2.3 on 2025-06-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fitur_app", "0010_rename_desa_id_checkupgroup_desa"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("task_duration", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "features",
                    models.ManyToManyField(
                        related_name="tasks", to="fitur_app.feature"
                    ),
                ),
            ],
        ),
    ]
